language: node_js
node_js: '7'
before_install: npm install -g eslint
script: npm test
deploy:
  provider: npm
  email: joe.fusco@verndale.com
  api_key:
    secure: N5OM6HC+nOkPHB6nWjOxcjyl4L9huxMWvclbZetX7OlSyg4AVXHGcAXbx5cavrZXJNOlikVRbylJPT5PKJLHcwqtnNW7dRyNb9FjG/yy/QS1IGH8wNZwLQ506B5lTK4ou245k7ST9IrOKgC9QrmWCjX1cCiwZDWbfd0P4vBYdv/wlMnryB6swcUndUL55FjTyqh9h32aZbrEbiLMvH/trwJ1vQK8cUJl4U6aacLes8h+mRpFQCmvEyiFi+LMHh4YEOZNcyG63nTnd22FQ7Id4urbxl2Rur7bUDQePTn/0+aAMXKQvixirVt6ptbcUKD5rzGkUJlqMBGD9odKBRD+vpUk6OAQXQ7mtHjx7tm9/CXNxgdC96ofQ58MuBHrvmURfPc45o5zqSdBvDKVGlAEHeUfxtefMV7ZWg+tbyW2qAz5eBMkmwilw8I2EwbVq9cY94DT4LgY5c+08X4kIi7SQoDkHzOz1lIeyJoT60/5BhC8JQfs9wyl1HvMGK4Ke5P23nrjKN0JDBnUldZYHHS1CtbdE8mcsOUwK1lVPjc4f722X7M+xSW0L2vh5I1FcOd1MK49AF9vB8vFZ9Pjs3Wo3wmUeSRjB9QoLYiCgC6/v8UGRN0eGHHxXejAg6gv7imIiOlEBh7FXfhTb3nMI6dj4r9xzrjKn9tbMn7OI9Me9C4=
  on:
    tags: true
